name: chats
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_theming:
    path: ../common/ui_theming
  ui_utils:
    path: ../common/ui_utils 
  ui_components:
    path: ../common/ui_components
  utils:
    path: ../common/utils
  auth:
    path: ../auth
  core:
    path: ../core
  matcher_service:
    path: ../matcher_service
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  retrofit: ^4.4.0
  dio: ^5.7.0
  sticky_grouped_list: 
    git: 
      url: https://github.com/Max-Size/sticky_grouped_list
  intl: ^0.20.1
  provider: ^6.1.2
  stomp_dart_client: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0'
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - packages/chats/assets/images/background.png
    - packages/chats/assets/images/no_chats.png
    - packages/chats/assets/icons/calendar.svg
    - packages/chats/assets/icons/place.svg
    - packages/chats/assets/icons/time.svg
    - packages/chats/assets/icons/gps.svg
    - packages/chats/assets/icons/place_fill.svg
    - packages/chats/assets/icons/logo.svg


