name: chats
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_theming:
    path: ../common/ui_theming
  ui_utils:
    path: ../common/ui_utils 
  ui_components:
    path: ../common/ui_components
  utils:
    path: ../common/utils
  core:
    path: ../core
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^8.1.6
  retrofit: ^4.4.0
  dio: ^5.7.0
  sticky_grouped_list: ^3.1.0
  intl: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0'
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - packages/chats/assets/images/background.png

