name: random_walk
description: "A new Flutter project."
publish_to: 'none' 

version: 0.0.7

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  utils:
    path: common/utils
  ui_components:
    path: common/ui_components
  ui_theming:
    path: common/ui_theming
  ui_utils:
    path: common/ui_utils 
  main:
    path: main
  auth:
    path: auth
  chats:
    path: chats
  core:
    path: core
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  flutter_bloc: ^8.1.6

# dependency_overrides:
#   maplibre_gl:
#     git:
#       url: https://github.com/maplibre/flutter-maplibre-gl.git
#       ref: main
#       path: maplibre_gl
#   maplibre_gl_web:
#     git:
#       url: https://github.com/maplibre/flutter-maplibre-gl.git
#       ref: main
#       path: maplibre_gl_web
#   maplibre_gl_platform_interface:
#     git:
#       url: https://github.com/maplibre/flutter-maplibre-gl.git
#       ref: main
#       path: maplibre_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.0.0 
  dartz: ^0.10.1
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.0.0
  drift: ^2.26.1

flutter:
  assets:
    - auth.env
  uses-material-design: true