name: main
description: "A new Flutter package project."
pubslish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chats:
    path: ../chats
  flutter_svg: ^2.0.10+1
  ui_theming:
    path: ../common/ui_theming
  ui_utils:
    path: ../common/ui_utils 
  ui_components:
    path: ../common/ui_components
  utils:
    path: ../common/utils
  core:
    path: ../core
  auth:
    path: ../auth
  matcher_service:
    path: ../matcher_service
  clubs:
    path: ../clubs
  flutter_bloc: ^8.1.6
  firebase_core: ^3.6.0
  firebase_messaging: ^15.2.5
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.1.0
  rxdart: ^0.28.0
  meta:
  universal_platform: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/main/assets/chat_fill.svg
    - packages/main/assets/chat.svg
    - packages/main/assets/group_fill.svg
    - packages/main/assets/group.svg
    - packages/main/assets/logo_fill.svg
    - packages/main/assets/logo.svg
    - packages/main/assets/settings_fill.svg
    - packages/main/assets/settings.svg
