name: matcher_service
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_theming:
    path: ../common/ui_theming
  ui_utils:
    path: ../common/ui_utils 
  ui_components:
    path: ../common/ui_components
  utils:
    path: ../common/utils
  auth:
    path: ../auth
  core:
    path: ../core
  clubs:
    path: ../clubs
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  retrofit: ^4.4.0
  dio: ^5.7.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0'
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - packages/matcher_service/assets/icons/checked.svg
    - packages/matcher_service/assets/icons/logo.svg
    - packages/matcher_service/assets/icons/search.svg
    - packages/matcher_service/assets/images/no_appointments.svg


  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
