name: auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_theming:
    path: ../common/ui_theming
  ui_utils:
    path: ../common/ui_utils 
  ui_components:
    path: ../common/ui_components
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - packages/auth/assets/icons/vk.svg
    - packages/auth/assets/icons/google.svg
    - packages/auth/assets/icons/yandex.svg
  uses-material-design: true
