name: ui_components
description: "A new Flutter package project."
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_utils:
    path: ../ui_utils
  ui_theming:
    path: ../ui_theming
  flutter_svg: ^2.0.10+1
  auth:
    path: ../../auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  assets:
    - packages/ui_components/assets/logo/random_walk_logo.svg
    - packages/ui_components/assets/icons/checked.svg
    - packages/ui_components/assets/icons/double_tick.svg
    - packages/ui_components/assets/icons/send.svg

  uses-material-design: true

