name: ui_components
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_utils:
    path: ../ui_utils
  ui_theming:
    path: ../ui_theming

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

