name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  dio: ^5.7.0
  auth:
    path: ../auth
  utils:
    path: ../common/utils
  ui_components:
    path: ../common/ui_components
  ui_utils:
    path: ../common/ui_utils
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  retrofit: ^4.4.0
  bloc_concurrency: ^0.2.5
  flutter_svg: ^2.0.10+1
  rxdart: ^0.28.0
  maplibre_gl: ^0.21.0
  geolocator: ^14.0.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.4.1

dependency_overrides:
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
      path: maplibre_gl
  maplibre_gl_web:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
      path: maplibre_gl_web
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
      path: maplibre_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0'
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.9.0
  drift_dev: ^2.26.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - packages/core/assets/place_fill.png
    - packages/core/assets/map_tiler_logo.png

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
