// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcm2P9q4OyO3gDY3h9Udkf0veWQCwxyKs',
    appId: '1:402464264412:android:33f6be819d43dafeea6419',
    messagingSenderId: '402464264412',
    projectId: 'random-walk-app',
    storageBucket: 'random-walk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5kLDfDTEoldNKg9LNpzy5dCI2EsWWLVk',
    appId: '1:402464264412:ios:bd98295f4b105c1aea6419',
    messagingSenderId: '402464264412',
    projectId: 'random-walk-app',
    storageBucket: 'random-walk-app.firebasestorage.app',
    androidClientId: '402464264412-2prm0d0kt01nbjoteko2askgepufdq10.apps.googleusercontent.com',
    iosClientId: '402464264412-lubf7quiitg4pnph132a9dpo7a9kf1k3.apps.googleusercontent.com',
    iosBundleId: 'ru.hse.random.walk',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7aQbzNeswUs11TSA2UxzKKrWX-Lzsnyo',
    appId: '1:402464264412:web:f275b2c4258b17d8ea6419',
    messagingSenderId: '402464264412',
    projectId: 'random-walk-app',
    authDomain: 'random-walk-app.firebaseapp.com',
    storageBucket: 'random-walk-app.firebasestorage.app',
    measurementId: 'G-YJPM0YS3N2',
  );

}