name: clubs
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_theming:
    path: ../common/ui_theming
  ui_utils:
    path: ../common/ui_utils 
  ui_components:
    path: ../common/ui_components
  utils:
    path: ../common/utils
  core:
    path: ../core
  auth:
    path: ../auth
  flutter_svg: ^2.0.10+1
  dio: ^5.8.0+1
  logger: ^2.5.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  provider: ^6.1.5
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - packages/clubs/assets/images/avatar.png
    - packages/clubs/assets/images/no_groups.png
    - packages/clubs/assets/icons/minus.svg
    - packages/clubs/assets/icons/plus.svg
    - packages/clubs/assets/icons/clubs.svg
    - packages/clubs/assets/icons/edit.svg
    - packages/clubs/assets/icons/delete.svg
    - packages/clubs/assets/icons/fail.svg
    - packages/clubs/assets/icons/success.svg
    - packages/clubs/assets/icons/search.svg
    - packages/clubs/assets/icons/image.svg


  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
