name: Update Golden Files

on:
  workflow_dispatch:  
  
jobs:
  update_golden:
    name: Update Golden Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Create fake auth.env for CI
        run: echo "FAKE_ENV_FOR_TESTS=true" > auth.env

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: |
          for pkg in auth chats core matcher_service; do
            echo "Processing $pkg"
            cd $pkg
            flutter pub get
            flutter pub run build_runner build --delete-conflicting-outputs
            cd ..
          done

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run golden tests with update
        run: xvfb-run --auto-servernum flutter test --tags=golden --update-goldens

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated golden files
        run: |
          git add .
          git diff --quiet || git commit -m "Update golden files"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/ru-random-walk/mobile_app.git main
